---
name: "Build"

jobs:
  dkms:
    name: "DKMS"
    strategy:
      matrix:
        distro:
          - name: "debian"
            tag: "11"
  runs-on: "ubuntu-20.04"
  container:
    image: "docker://docker.io/library/${{ matrix.distro.name }}:${{ matrix.distro.tag }}"

  steps:
    - uses: "actions/checkout@v2"
    - name: "Install Debian Dependencies"
      if: matrix.distro.name == "debian"
      run: |
        apt-get update -q
        apt-get install -qy dkms
    - name: "Copy files"
      run: |
        mkdir /usr/src/cm4io-fan-${GITHUB_SHA::8}
        git archive HEAD | tar -x -C "/usr/src/cm4io-fan-${GITHUB_SHA::8}"
    - name: "Build"
      run: |
        dkms build cm4io-fan/${GITHUB_SHA::8}
