---
name: "Build"

on:
  push:
  pull_request:

jobs:
  dkms:
    name: "DKMS"
    strategy:
      matrix:
        distro:
          - name: "debian"
            tag: "11"
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
    container:
      image: "docker://docker.io/library/${{ matrix.distro.name }}:${{ matrix.distro.tag }}"

    steps:
      - uses: "actions/checkout@v2"
      - name: "Install Debian Dependencies"
        if: matrix.distro.name == 'debian'
        run: |
          apt-get update -q
          apt-get install -qy dkms
      - name: "Link files"
        run: |
          ln -s . /usr/src/cm4io-fan-${GITHUB_SHA}
      - name: "Debug"
        run: |
          ls -l /usr/src/
          ls -l /usr/src/cm4io-fan-${GITHUB_SHA}/
      - name: "Build"
        run: |
          dkms build cm4io-fan/${GITHUB_SHA}
